---
notifications:
  email:
  - team@appwrite.io

language: minimal

arch:
  - amd64
  - arm64
  - ppc64le

os: linux

env:
  - CRYPTOGRAPHY_ALLOW_OPENSSL_102=true

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
  - docker --version

install:
  - docker-compose up -d

script:
  - sleep 10
  - docker ps -a
  - docker-compose logs mariadb
  - docker-compose exec -T mariadb ls /docker-entrypoint-initdb.d
  - docker-compose exec -T mariadb cat /docker-entrypoint-initdb.d/all.sql
  - docker-compose exec -T mariadb mysqldump --user=root --password=rootsecretpassword appwrite

deploy:
  - provider: script
    edge: true
    script: docker run --rm --privileged linuxkit/binfmt:v0.8 &&
      docker buildx create --use &&
      docker buildx build --platform linux/amd64,linux/arm64/v8,linux/ppc64le -t appwrite/mariadb:$TRAVIS_TAG ./ --push
    on:
      tags: true
      condition: "$TRAVIS_CPU_ARCH = amd64"
