---
version: '3'

services:
  mariadb:
    build: .
    container_name: db-mariadb
    restart: unless-stopped
    networks:
      - db
    volumes:
      - db-mariadb:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecretpassword
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: 'mysqld --innodb-flush-method=fsync'

networks:
  db:

volumes:
  db-mariadb:

