---
version: '3'

services:
  mariadb:
    build: .
    container_name: db-mariadb
    restart: unless-stopped
    networks:
      - db
    volumes:
      - db-mariadb:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=rootsecretpassword
      - MARIADB_DATABASE=appwrite
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_AUTO_UPGRADE=1
    command: '--innodb-flush-method=fsync'

networks:
  db:

volumes:
  db-mariadb:
